# Generated by Django 3.1.5 on 2021-02-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supercars',
            new_name='Product',
        ),
    ]
